### ISSUE TITLE
Allow receiving payments via NWC and checking payment status

### ISSUE THREAD

**Issue by supertestnet** [cashubtc/cashu.me#196]
Most NWC wallets let you send *and* receive money. And they also let you check the status of both incoming payments and outgoing payments so you can see if you've been paid or if your outgoing payment went through. Please add support for these features.

**Comment by ekzyis** [comment]
When receiving is supported, this would ideally also be available as a separate connection. With only one connection that also supports spending, they can still only use this wallet for sending with SN since we have to keep receive permissions separated from send.

I will take a look into this when I have time.

**Comment by supertestnet** [comment]
> With only one connection that also supports spending, they can still only use this wallet for sending

I don't see why. If a user wants to treat cashu.me as a backend, then any frontend they connect it to can both send and receive via the same connection string. Some frontends require separate strings for sending and receiving (e.g. stacker news) but others don't (e.g. [brick wallet](https://github.com/supertestnet/brick-wallet/))

**Comment by ekzyis** [comment]
Yes, I was only talking about SN. If receive is not separated from send, then you can't use receive on SN :/
